spring.application.name=bitovi-weather-mcp-server
server.port=8081
logging.level.web=DEBUG
spring.main.bannerMode=off
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"